matrix:
  include:
    - os: osx
      osx_image: xcode8.1
      language: objective-c
      env:
        - QUICK_POD_LINT=true
    - os: osx
      osx_image: xcode8.3
      language: objective-c
      env:
        - QUICK_POD_LINT=false
    - os: osx
      osx_image: xcode9
      language: objective-c
      env:
        - QUICK_POD_LINT=true
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION="3.0.2"
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION="3.1"
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION="3.1.1"
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION="4.0-DEVELOPMENT-SNAPSHOT-2017-08-04-a"
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="RandomKit"
    - SWIFTENV_ROOT="$HOME/.swiftenv"
    - PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
install: ./ci/install.sh
script: ./ci/travis.sh
