matrix:
  include:
    - os: osx
      osx_image: xcode8.1
      language: objective-c
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        matrix:
          - SWIFT_VERSION=swift-3.1
          - SWIFT_VERSION=swift-3.0.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="RandomKit"
    - SWIFTENV_INSTALL="https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gem install xcpretty -N; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL $SWIFTENV_INSTALL)"; fi
script: ./ci/travis.sh
